import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const read = (path) => fs.readFileSync(path, "utf8");
const wireGuardHelperPath = path.resolve("scripts/prepare-wireguard.helpers.ps1");
const hasPowerShellCore = () => {
  const result = spawnSync("pwsh", ["-NoProfile", "-Command", "exit 0"], {
    stdio: "ignore",
  });

  return !result.error && result.status === 0;
};

test("Windows validation asserts the authoritative build identity", () => {
  const build = JSON.parse(read("build-version.json"));
  const workflow = read(".github/workflows/windows-build-1-04-validation.yml");

  assert.match(workflow, new RegExp(`name: CinaVault Premium ${build.displayName.replaceAll(".", "\\.")} Windows Validation`));
  assert.match(workflow, new RegExp(`displayName -ne '${build.displayName.replaceAll(".", "\\.")}'`));
  assert.match(workflow, new RegExp(`semanticVersion -ne '${build.semanticVersion.replaceAll(".", "\\.")}'`));
  assert.match(workflow, new RegExp(`releaseTag -ne '${build.releaseTag.replaceAll(".", "\\.")}'`));
});

test("SonarCloud analysis skips clearly unless all secret configuration exists", () => {
  const workflow = read(".github/workflows/sonarcloud.yml");

  assert.match(workflow, /SonarCloud configuration notice/);
  assert.match(workflow, /SONAR_TOKEN: \$\{\{ secrets\.SONAR_TOKEN \}\}/);
  assert.match(workflow, /SONAR_PROJECT_KEY: \$\{\{ vars\.SONAR_PROJECT_KEY \}\}/);
  assert.match(workflow, /SONAR_ORGANIZATION: \$\{\{ vars\.SONAR_ORGANIZATION \}\}/);
  assert.match(workflow, /env\.SONAR_TOKEN == '' \|\| env\.SONAR_PROJECT_KEY == '' \|\| env\.SONAR_ORGANIZATION == ''/);
  assert.match(workflow, /env\.SONAR_TOKEN != '' && env\.SONAR_PROJECT_KEY != '' && env\.SONAR_ORGANIZATION != ''/);
  assert.doesNotMatch(workflow, /if:.*secrets\./);
  assert.match(workflow, /::notice title=SonarCloud skipped/);
  assert.doesNotMatch(workflow, /-Dsonar\.(?:projectKey|organization)=\s*$/m);
});

test("Cargo lockfile is reproducible UTF-8 TOML", () => {
  const lockfile = read("src-tauri/Cargo.lock");

  assert.match(lockfile, /^# This file is automatically @generated by Cargo\./);
  assert.match(lockfile, /^version = 4$/m);
  assert.match(lockfile, /^\[\[package\]\]$/m);
});

test("WireGuard preparation accepts the official signer identity", (t) => {
  if (!hasPowerShellCore()) {
    t.skip("pwsh is not available");
  }

  const output = execFileSync(
    "pwsh",
    [
      "-NoProfile",
      "-Command",
      `. '${wireGuardHelperPath.replace(/'/g, "''")}'; ` +
        "$trustedSubject = Test-OfficialWireGuardSignerSubject -SignatureLike ([pscustomobject]@{ Subject = 'CN=WireGuard LLC, O=WireGuard LLC' }); " +
        "$legacySubject = Test-OfficialWireGuardSignerSubject -SignatureLike ([pscustomobject]@{ Subject = 'CN=Jason A. Donenfeld' }); " +
        "$trustedFallback = Test-OfficialWireGuardSignerSubject -SignatureLike ([pscustomobject]@{ SimpleName = 'WireGuard LLC'; Subject = 'WireGuard LLC' }); " +
        "$mismatch = Test-OfficialWireGuardSignerSubject -SignatureLike ([pscustomobject]@{ SimpleName = 'WireGuard LLC'; Subject = 'CN=AAA Certificate Services, O=WireGuard LLC' }); " +
        'Write-Output \"$trustedSubject,$legacySubject,$trustedFallback,$mismatch\"',
    ],
    { encoding: "utf8" },
  ).trim();

  assert.equal(output, "True,True,True,False");
});

test("WireGuard preparation accepts valid MSI signatures but rejects non-official executable publishers", (t) => {
  if (!hasPowerShellCore()) {
    t.skip("pwsh is not available");
  }

  const tempDirectory = fs.mkdtempSync(
    path.join(os.tmpdir(), "ci-wireguard-validation-"),
  );
  const tempScriptPath = path.join(tempDirectory, "validate-wireguard.ps1");
  fs.writeFileSync(
    tempScriptPath,
    `. '${wireGuardHelperPath.replace(/'/g, "''")}'
function Get-CodeSignature {
    param([Parameter(Mandatory = $true)][string]$Path)

    switch ($Path) {
        'msi-valid' {
            return [pscustomobject]@{
                Status = 'Valid'
                SignerCertificate = [pscustomobject]@{
                    Subject = 'CN=AAA Certificate Services, O=AAA Certificate Services'
                    SimpleName = 'AAA Certificate Services'
                }
            }
        }
        'exe-valid-subject' {
            return [pscustomobject]@{
                Status = 'Valid'
                SignerCertificate = [pscustomobject]@{
                    Subject = 'CN=WireGuard LLC, O=WireGuard LLC'
                }
            }
        }
        'exe-valid-fallback' {
            return [pscustomobject]@{
                Status = 'Valid'
                SignerCertificate = [pscustomobject]@{
                    Subject = 'WireGuard LLC'
                    SimpleName = 'WireGuard LLC'
                }
            }
        }
        'exe-subject-mismatch' {
            return [pscustomobject]@{
                Status = 'Valid'
                SignerCertificate = [pscustomobject]@{
                    Subject = 'CN=AAA Certificate Services, O=WireGuard LLC'
                    SimpleName = 'WireGuard LLC'
                }
            }
        }
        default {
            throw "Unexpected path: $Path"
        }
    }
}

Assert-AuthenticodeSignature -Path 'msi-valid' -Label 'Downloaded WireGuard MSI' | Out-Null
Assert-AuthenticodeSignature -Path 'exe-valid-subject' -Label 'WireGuard executable' -RequireOfficialWireGuardSigner | Out-Null
Assert-AuthenticodeSignature -Path 'exe-valid-fallback' -Label 'WireGuard executable' -RequireOfficialWireGuardSigner | Out-Null

try {
    Assert-AuthenticodeSignature -Path 'exe-subject-mismatch' -Label 'WireGuard executable' -RequireOfficialWireGuardSigner | Out-Null
    Write-Output 'unexpected-pass'
}
catch {
    Write-Output $_.Exception.Message
}
`,
    "utf8",
  );

  try {
    const output = execFileSync("pwsh", ["-NoProfile", "-File", tempScriptPath], {
      encoding: "utf8",
    });

    assert.doesNotMatch(output, /unexpected-pass/);
    assert.match(output, /WireGuard executable is Authenticode-signed but not by a trusted official WireGuard publisher/);
  } finally {
    fs.rmSync(tempDirectory, { force: true, recursive: true });
  }
});

test("WireGuard preparation reports when PowerShell signature tooling is unavailable", (t) => {
  if (!hasPowerShellCore()) {
    t.skip("pwsh is not available");
  }

  const tempDirectory = fs.mkdtempSync(
    path.join(os.tmpdir(), "ci-wireguard-missing-signature-tooling-"),
  );
  const tempScriptPath = path.join(tempDirectory, "missing-signature-tooling.ps1");
  fs.writeFileSync(
    tempScriptPath,
    `. '${wireGuardHelperPath.replace(/'/g, "''")}'
function Import-Module {
    throw 'module unavailable'
}

function Get-Command {
    param()
    return $null
}

try {
    Get-CodeSignature -Path 'wireguard.exe' | Out-Null
    Write-Output 'unexpected-pass'
}
catch {
    Write-Output $_.Exception.Message
}
`,
    "utf8",
  );

  try {
    const output = execFileSync("pwsh", ["-NoProfile", "-File", tempScriptPath], {
      encoding: "utf8",
    });

    assert.doesNotMatch(output, /unexpected-pass/);
    assert.match(output, /Microsoft\.PowerShell\.Security and signtool\.exe are unavailable/);
  } finally {
    fs.rmSync(tempDirectory, { force: true, recursive: true });
  }
});
